"""added-Logged-Exercise-Table-and-corrected-tablename

Revision ID: 20dc06fd4728
Revises: b9fb265844dc
Create Date: 2023-06-28 11:23:36.636034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20dc06fd4728'
down_revision = 'b9fb265844dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loggedexercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.String(length=4), nullable=True),
    sa.Column('exercise_name', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('sets_completed', sa.Integer(), nullable=True),
    sa.Column('weight_used', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_loggedexercises_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('completedworkouts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completedworkouts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('exercise_id', sa.VARCHAR(length=4), nullable=True),
    sa.Column('exercise_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('sets_completed', sa.INTEGER(), nullable=True),
    sa.Column('weight_used', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_completedworkouts_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('loggedexercises')
    # ### end Alembic commands ###
