"""Updated User Model

Revision ID: 349bd96a6441
Revises: d5df177c0e2a
Create Date: 2023-06-19 12:00:40.894949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349bd96a6441'
down_revision = 'd5df177c0e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
